[package]
name = "index"
version = "1.0.0"
authors = ["Fredrik Pettersen <fredrik.fumler@gmail.com>"]
edition = "2018"

[dependencies]
http = "0.1"
vercel_lambda = "*"
check-if-email-exists = "0.8"
serde = "1.0.130"
serde_json = "1.0.67"
futures = "0.3"

[lib]
name = "util"
path = "_util.rs"